name: Deploy on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.18.2"

      - name: Install dependencies
        run: npm install

      - name: Set Git user
        run: |
          git config user.email "dominiclingham@outlook.com"
          git config user.name "DominicLingham"

      - name: Build and deploy to GitHub Pages
        run: |
          npm run deploy
        env:
          NODE_ENV: production
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
