name: Deployment Trigger

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.18.2"
      - run: npm install

      - run: npm run predeploy

      - name: Run Cypress Tests
        run: |
          npm run dev & # Run your local server in the background
          npx cypress run --config baseUrl=http://localhost:3000
          kill $(jobs -p)

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: ./dist
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
